Add loading property
morbidick/stripe-elements pull request #10
Opened 2017-11-12 11:41 UTC by RoXuS

Hey !

Thx for your element !!

I just add a commit to display a loader while the token is created.

And an other commit to set displayError as a public method. The we will use the component to display the other errors from Stripe API.

2017-11-13 13:51 UTC, morbidick commented
Hi,
thanks for your PR.
Just one thing, if we have `displayError` as public method we should add a check for [Line 254](https://github.com/RoXuS/stripe-elements/blob/e04e3707e049fe7c48b98033d7237ee19eb82f57/stripe-card.html#L254) to not run into any errors where `param` is set with no matching form element. Would you mind adding another commit?

2017-11-13 21:35 UTC, RoXuS commented
Hi @morbidick,
Good catch, I have added the check, it is ok for you ?

2017-11-14 14:17 UTC, morbidick requested changes
Thank your for your commit, reverting the whitespace changes and we can get this merged! The travis build fail is my mistake, i planned to at a travis lint job for the next release as soon as this is merged.

2017-11-14 14:17 UTC, morbidick commented on stripe-card.html
> +          if (element) {
the check looks good, nice change with `querySelector` i like it :+1:

2017-11-14 14:17 UTC, morbidick commented on stripe-card.html
> +</dom-module>
A lot of whitespace got added with this commit, and this one removed, could you revert those changes?

2017-11-14 21:26 UTC, RoXuS commented
Oh yeah sorry @morbidick, it's my IDE which auto format the code following my eslint conf ^^.

I rebase the last commit to avoid all whitespaces. It should be ok !

2017-11-15 13:09 UTC, merged

2017-11-15 13:10 UTC, morbidick commented
Thank you very much @RoXuS, Im going to update `analysis.json` and push a new release.