Some fixes
morbidick/stripe-elements pull request #12
Opened 2018-06-03 09:01 UTC by RoXuS

Hello !

I have added a way to set the submit text (to handling i18n).
I have set the loading to false in case of error on form.

Thx !

2018-06-03 15:05 UTC, morbidick requested changes
Thanks for the label improvement, would you mind removing the second commit? that case is already handled. I'll look into updating the failing CI.

2018-06-03 15:05 UTC, morbidick commented on stripe-card.html
> +          <paper-button on-click="_submit">[[submitLabel]]</paper-button>
Looks good and makes sense

2018-06-03 15:05 UTC, morbidick commented on stripe-card.html
> +          this.loading = false;
This should be already done by the catch in the `createToken` function

2018-06-03 19:33 UTC, RoXuS commented
Done, thx for your response !

2018-06-03 19:53 UTC, RoXuS commented
@morbidick I have tested without the `this.loading = false` in promise catch and it is not handled by the try/catch, so after an error on form, the loading is never set to false !

2018-06-03 21:13 UTC, merged

2018-06-04 08:58 UTC, morbidick commented
CI updated and version 2.5.0 released :tada: